### PR TITLE
mark unsafe methods

### PR DESCRIPTION
**Pull request by danieleades**
see https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref

### CODE REVIEW

**Comment by danieleades** [comment]
looking at the signature of `deallocate_segment` it's kind of wild that this method is *not* already marked as unsafe. I imagine this change provides some impetus to cutting a new release in the near future?

**Comment by dwrensha** [comment]
That's a method that's not intended to be called by end users. We have a lot of other such methods under the `private` module that arguably should also be marked `unsafe`, e.g. `PointerReader::get_root()`, but I'm not too worried about any of them because it's pretty clear that they are not intended as public API.

For now, I think expanding the doc comment on `deallocate_segment()` would be sufficient.

**Comment by dwrensha** [comment]
(I do think we should clean these things up, but I don't think it's urgent enough that we need to rush out a new release.)

**Comment by danieleades** [comment]
> because it's pretty clear that they are not intended as public API

surely this means that correctly marking them as unsafe is then *not* a breaking change?

**Comment by dwrensha** [comment]
> surely this means that correctly marking them as unsafe is then not a breaking change?

Users are supposed to be able to implement the `Allocator` trait, but are not supposed to call it directly. This change is breaking for uses implement the `Allocator` trait.

**Comment by dwrensha** [comment]
rebased and merged in https://github.com/capnproto/capnproto-rust/commit/1d4c541604a2788dfaee41ae5f31322781e5b85d

**Pull request closed without merging**
