### PR TITLE
ignore coverage for benchmarks and examples

### PR DESCRIPTION
**Pull request by danieleades**
ignore benchmarks and examples which are artificially lowering the coverage.

### CODE REVIEW

**Comment by danieleades** [comment]
codecov should be posting coverage diffs on the PRs by the way. @dwrensha not sure if you need to toggle anything on over at https://app.codecov.io/github/capnproto/capnproto-rust?

Occasionally the codecov bot is impacted by rate limiting of the github API it uses so it could just be related to that

**Comment by danieleades** [comment]
i'll leave this as a draft until i can confirm the report is updating as expected

**Comment by dwrensha** [comment]
I clicked around a bunch, bunch I don't think I changed any settings.

I did notice on #461 that codecov failed on the upload step like this:
```
Run codecov/codecov-action@v3
==> linux OS detected
https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (b9282b8b43eef83f722646d8992c4dd36563046afe0806722184e7e9923a6d7b  codecov)
==> Running version latest
==> Running version v0.7.1
/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov -n  -Q github-action-3.1.4 -f lcov.info -C 7e6247fa6b15e3314a9314d942b2c7a7f571588d
[2023-11-29T17:10:39.371Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.7.1
[2023-11-29T17:10:39.379Z] ['info'] => Project root located at: /home/runner/work/capnproto-rust/capnproto-rust
[2023-11-29T17:10:39.380Z] ['info'] -> No token specified or token is empty
[2023-11-29T17:10:39.388Z] ['info'] Searching for coverage files...
[2023-11-29T17:10:39.455Z] ['info'] => Found 1 possible coverage files:
  lcov.info
[2023-11-29T17:10:39.455Z] ['info'] Processing /home/runner/work/capnproto-rust/capnproto-rust/lcov.info...
[2023-11-29T17:10:39.571Z] ['info'] Detected GitHub Actions as the CI provider.
[2023-11-29T17:10:39.864Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-3.1.4-uploader-0.7.1&token=*******&branch=coverage-build-script&build=7035998763&build_url=https%3A%2F%2Fgithub.com%2Fcapnproto%2Fcapnproto-rust%2Factions%2Fruns%2F7035998763%2Fjob%2F19147778790&commit=7e6247fa6b15e3314a9314d942b2c7a7f571588d&job=Code+Coverage&pr=461&service=github-actions&slug=capnproto%2Fcapnproto-rust&name=&tag=&flags=&parent=
[2023-11-29T17:10:40.064Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

Weirdly, the overall run was still reported as a success.

**Comment by dwrensha** [comment]
I logged into codecov.com and gave the app permission on this repo. Maybe that will help.

**Comment by danieleades** [comment]
> I logged into codecov.com and gave the app permission on this repo. Maybe that will help.

i've also added the token to the github action, but you'll need to add the token to the repo 'secrets' for that to work

**Pull request merged**
