### PR TITLE
WIP: futures_preview 0.3

### PR DESCRIPTION
**Pull request by vhdirk**
This is a feeble attempt at getting capnproto-rs to work with futures-preview 0.3.0-alpha. It's not finished by a long shot, and I doubt I'll be able to do that on my own. 
I haven't even gotten this to compile yet, but I've fixed most of the API differences with futures 0.1.

Given the vast amount of changes in futures, especially the addition of the ```AsyncRead``` and ```AsyncWrite``` traits, It could be possible to eliminate a considerable amount of code here. But that's probably a lot of work that I have absolutely no time for :)

### CODE REVIEW

**Comment by vhdirk** [comment]
Hi @dwrensha 
I'm eager to get this working. Could you elaborate on how you'd like to tackle this?

**Comment by dwrensha** [comment]
I see that you've found my [std-future](https://github.com/capnproto/capnproto-rust/tree/std-future) branch. :)

Looks like `std::future` is on track to be stabilized in 1.36, at which point we could potentially make a release that depends on it. I do wish I knew the story for the `futures` crate -- are they going to publish a 1.0 version soon after rust 1.36 comes out? I think it's going to be unavoidable that some of our interfaces will contain futures types that are not (yet) in `std` (e.g. `Stream` or `AsyncRead`) -- it would be best if these were stable versions of these types.

My plan is to keep working on the std-futures branch and shoot for a release later in the summer. At this point it's looking like it I'll try to do the minimal possible migration to get things to work with the new futures library. You're welcome to try to make progress on this front yourself, but I'm not sure how much guidance I can offer.

**Comment by vhdirk** [comment]
@dwrensha at this point, I'm not even aiming at a release, so I'm fine with this being on a separate branch.
There's a couple of features that seem notably absent in the 0.3 api. For instance, spawning new tasks on the 'current' executor. I'm not sure how to solve that yet.
It seems mostly that and the new Pin requirements.

**Comment by dwrensha** [comment]
I've been making steady progress on the [std-future](https://github.com/capnproto/capnproto-rust/tree/std-future) branch. As of now, almost all of the capnp-rpc tests pass, and the calculator and pubsub examples are working.

**Comment by vhdirk** [comment]
I noticed that just yesterday. Awesome! I'll put it to the tests asap.

**Pull request closed without merging**
