### PR TITLE
Add the OwnedReader as proposed in #50

### PR DESCRIPTION
**Pull request by bspeice**
Should also provide solutions for #23 and #75

### CODE REVIEW

**Comment by dwrensha** [comment]
Thanks! I think we should also include the `get()` method as discussed in #50. Also, looks like you need to adjust some of the paths to get this to typecheck.

**Comment by bspeice** [comment]
Fixed up, let me know if there are any other concerns.

**Comment by dwrensha** [comment]
Hm. Now I'm thinking that `message::TypedReader` or similar might be a better name. The difference from `message::Reader` does not have to do with ownership actually -- it has to do with the extra type parameter `T`.

**Comment by bspeice** [comment]
Ah, because we're no longer forcing the `OwnedSegments`. It's a trivial fix, just let me know.
What I do think may be more important - Should I add more to the docs/test cases to demonstrate moving across thread boundaries?

**Comment by dwrensha** [comment]
OK, I'll merge this as-is and then fix up the names myself. Please feel free to submit new pull requests for docs and tests.

**Comment by dwrensha** [comment]
renamed in https://github.com/capnproto/capnproto-rust/commit/f0efc35d7e9bd8f97ca4fdeb7c57fd7ea348e303

**Pull request merged**
