### PR TITLE
Add write_message_segments/write_message_segments_to_words

### PR DESCRIPTION
**Pull request by polachok**
I'm not sure if I'm taking the right approach here, just wanted to gather feedback

https://github.com/capnproto/capnpc-rust/issues/45

### CODE REVIEW

**Comment by dwrensha** [comment]
Thanks! I'll probably have a chance to take a look this weekend...

**Comment by dwrensha** [comment]
This looks pretty good to me.

It's sad that we need the `get_reader_segment_count()` function. Maybe we should instead add a `len(&self) -> u32` method to `ReaderSegments`. At one point I think we may have been considering doing something fancy with `ReaderSegments` being sparsely populated, but now that seems to me unlikely to work out. A new `len()` method would need a default impl in order to be a non-breaking change.

**Comment by polachok** [comment]
PR updated with len() method

**Comment by dwrensha** [comment]
Thanks!

**Pull request merged**
