### PR TITLE
Lookup super interfaces recursively

### PR DESCRIPTION
**Pull request by zortax**
Currently, only one level of interface inheritance is supported. This PR adds a recursive lookup to support multiple levels.

### CODE REVIEW

**Comment by dwrensha** [comment]
What's an example of a schema that does not work before this change?

**Comment by zortax** [comment]
```capnp
interface A {
    someMethod @1 ();
}

interface B extends(A) {}

interface C extends(B) {}
```

calling `someMethod` on a `C`-client causes a Method-not-implemented error, as the type ID of that call doesn't match the interface nor the direct super interface (there was no branch calling the correct ServerDispatch in the type id match statement being generated)

**Comment by zortax** [comment]
@dwrensha any chance this could be merged soon?

**Comment by dwrensha** [comment]
Thanks!

**Pull request merged**
