### PR TITLE
add test coverage workflow

### PR DESCRIPTION
**Pull request by danieleades**
adds a test coverage workflow

job result here - https://app.codecov.io/github/capnproto/capnproto-rust/tree/ci-coverage

### CODE REVIEW

**Comment by dwrensha** [comment]
Cool!

**Comment by dwrensha** [comment]
Do the tests in `capnpc/test/test.rs` count towards the coverage of `capnpc/`? I pushed https://github.com/capnproto/capnproto-rust/commit/a95d3e3adc41dd83b4575512f795430049ed6b27 and I expected it to increase the reported coverage of `target_size()`, but it seems that it did not: https://app.codecov.io/github/capnproto/capnproto-rust/commit/a95d3e3adc41dd83b4575512f795430049ed6b27/blob/capnp/src/private/layout.rs#L748

**Comment by danieleades** [comment]
> Do the tests in `capnpc/test/test.rs` count towards the coverage of `capnpc/`? I pushed [a95d3e3](https://github.com/capnproto/capnproto-rust/commit/a95d3e3adc41dd83b4575512f795430049ed6b27) and I expected it to increase the reported coverage of `target_size()`, but it seems that it did not: https://app.codecov.io/github/capnproto/capnproto-rust/commit/a95d3e3adc41dd83b4575512f795430049ed6b27/blob/capnp/src/private/layout.rs#L748

the coverage should be counted so long as the following command runs those tests-

```sh
          for features in \
            "--no-default-features" \
            "--features sync_reader" \
            "--features unaligned"
          do
            cargo llvm-cov --no-report --doctests --workspace $features
```

or equivalently if this command runs those tests-

```sh
          for features in \
            "--no-default-features" \
            "--features sync_reader" \
            "--features unaligned"
          do
            cargo test --doctests --workspace $features
```

does that command run the tests you're talking about?

**Comment by dwrensha** [comment]
Aha, it looks like I expect after https://github.com/capnproto/capnproto-rust/commit/d27e043fb0128b4e0eff6292a73e365dd05c9b17:
 https://app.codecov.io/github/capnproto/capnproto-rust/commit/d27e043fb0128b4e0eff6292a73e365dd05c9b17/blob/capnp/src/private/layout.rs#L748

**Pull request merged**
