### PR TITLE
Convert (consume) Builder into TypedReader

### PR DESCRIPTION
**Pull request by bspeice**
Accidentally PR'd into my forked master, not original repo master.
Addresses capnproto/capnproto-rust#83

### CODE REVIEW

**Comment by bspeice** [comment]
I don't know how we should handle the ReaderOptions - I.e. is it safe to just use the default, or should I expose the ability to pass in an external ReaderOptions?

**Comment by dwrensha** [comment]
`ReaderOptions.traversal_limit_in_words` and `ReaderOptions.nesting_limit` exist to deal with untrusted data. When you have a `message::Builder`, you must have constructed the data yourself, so it's safe to set both of those options to `max_value()`. I think that's the right thing to do here.

Note that it also might make sense to convert a `message::Builder` to a `message::Reader` without going to a `message::TypedReader`, and it might make sense to have a `message::TypedBuilder` in the future. So I think it makes more sense to have separate methods: `message::Builder::into_reader()` and `message::Reader::into_typed()`.  We may also want to add an `message::TypedReader::into_inner()` message to allow recovering the reader.

**Comment by bspeice** [comment]
Idiomatic Rust question then - Should it just be `TypedReader` [`From`](https://doc.rust-lang.org/std/convert/trait.From.html) both `message::Builder` and `message::Reader`? Saves one extra function call (`builder.into_reader().into_typed()`) and uses the Rust API's for it.

**Comment by dwrensha** [comment]
I prefer adding methods with self-explanatory names like `into_reader()` and `into_typed()`. We could impl `From` on top of those methods, if we want that too.

**Comment by bspeice** [comment]
All the above are done. Let me know if there's anything else, sorry about the wait on this one.

**Comment by dwrensha** [comment]
Thanks!

**Comment by dwrensha** [comment]
Hm... it occurs to me that the rest of the codebase uses methods named `as_reader()` instead of `into_reader()` for this kind of situation. I wonder if it makes sense to use that naming scheme here also, for the sake of consistency (even if `into_*()` is more idiomatic in the wider Rust community).

**Comment by dwrensha** [comment]
`into_reader()` had an unnecessary type parameter: https://github.com/capnproto/capnproto-rust/commit/5bb2b41b704ea03ab3b4f08fab97e156b2a50da8

**Comment by dwrensha** [comment]
After further reflection, I think the `into_` prefix is correct here. It signifies that the ownership is being transferred. In constrast, a prefix of `as_` usually signifies that something is being borrowed. It's true that many `as_reader` methods in capnproto-rust (e.g. [this one](https://github.com/capnproto/capnproto-rust/blob/5bb2b41b704ea03ab3b4f08fab97e156b2a50da8/src/struct_list.rs#L105)) technically take `self` by value, but their usual intended use case is more like borrowing, in particular when they are used in conjunction with a `borrow()` method. (See [this blog post](https://dwrensha.github.io/capnproto-rust/2014/12/27/custom-mutable-references.html) for more discussion of these methods.)

**Pull request merged**
